# Generated by Django 5.1.8 on 2025-04-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_notesmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
