# Generated by Django 5.1.8 on 2025-04-18 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_alter_notesmodel_body_alter_notesmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
